// 键盘输入捕获，捕获到Esc键退出程序(Generated by ChatGLM)
#include <iostream>     // 提供输入输出流对象，如 cin 和 cout ，用于控制台输入输出。
#include <stdio.h>      // 提供标准输入输出函数，如 printf 和 scanf ，用于控制台输入输出。
#include <memory>       // 智能指针等内存管理功能，用于自动资源管理。
#include <unistd.h>     // 包含许多Unix标准系统调用和函数，像 read 、 write 、 close 等，用于文件操作、进程控制等。
#include "KeyDef.hpp"
#include "GpioDef.hpp"
#include "test.hpp"

int test_keyboard_read(void) {
    std::shared_ptr<KeyDef> kb = std::make_shared<KeyDef>();
    std::shared_ptr<GpioDef> led = std::make_shared<GpioDef>(83, MODE_OUT); // 初始化LED引脚
    printf("Press any key (ESC to exit):\n");
    while(true) {
        if ( kb->kbhit() ) { // 检测是否有键盘输入
            char c = kb->readKey(); // 读取字符
            if (c == KEY_ESC) break;
            printf("You pressed: %c\n", c);

            // 在这里可以执行其他任务 begin
            if(c == KEY_SPACE) led->setVal( !led->getVal() );
            // 在这里可以执行其他任务 end
        }

        // usleep(10); // 等待10ms
    }
    return 0;
}